export type Locale='ko'|'en';
const key='snapdeck.locale';
const pairs=[
['내 워크스페이스','My workspace'],['캡처 스튜디오','Capture Studio'],['내 보관함','My Library'],['로그인 세션','Login Sessions'],['사용 가이드','User Guide'],['워크스페이스','Workspace'],['로컬 엔진 연결됨','Local engine connected'],['웹 체험 버전','Web demo'],
['당신의 리서치는, 당신의 것.','Your research stays yours.'],['캡처와 문서 작업을','Keep captures and documents'],['내 기기 안에서 안전하게.','securely on your device.'],['로컬 처리 알아보기','Learn about local processing'],
['웹페이지를,','Turn web pages into'],['한 장의 인사이트로.','clear insights.'],['다시 꺼내 보는 리서치.','Research worth revisiting.'],['링크를 모으고, 깔끔하게 캡처하고, 바로 공유할 문서로 완성하세요.','Collect links, capture cleanly, and create documents ready to share.'],['이 브라우저 또는 앱에 저장된 프로젝트입니다.','Projects saved in this browser or app.'],['새 프로젝트','New Project'],
['링크 모으기','Collect Links'],['최대 300개','Up to 300'],['URL 입력','Enter URLs'],['파일 가져오기','Import File'],['URL을 한 줄에 하나씩 붙여넣으세요.','Paste one URL per line.'],['파일을 여기에 놓으세요','Drop the file here'],['중복 링크는 자동으로 정리해요','Duplicates are removed automatically'],['목록에 추가','Add to List'],['TXT, CSV, XLSX 파일을 끌어 놓아도 좋아요.','You can also drop a TXT, CSV, or XLSX file.'],
['캡처 설정','Capture Settings'],['디바이스','Device'],['데스크톱','Desktop'],['노트북','Laptop'],['태블릿','Tablet'],['모바일','Mobile'],['캡처 영역','Capture Area'],['첫 화면','Viewport'],['전체 페이지','Full Page'],['특정 영역','Selected Area'],['클린 캡처','Clean Capture'],['쿠키 배너와 채팅 위젯을 숨겨 깔끔하게','Hide cookie banners and chat widgets'],['사용하지 않음','Do not use'],['캡처 중지','Stop Capture'],['캡처 시작하기','Start Capture'],['내 기기에서 캡처 · 서버 업로드 없음','Captured on your device · No server upload'],['실제 URL 캡처는 데스크톱 앱에서 실행됩니다.','Live URL capture runs in the desktop app.'],
['문서 완성하기','Create Document'],['프로젝트 이름','Project Name'],['내보내기 형식','Export Format'],['프레젠테이션','presentation'],['스프레드시트','spreadsheet'],['슬라이드 레이아웃','Slide Layout'],['시트 레이아웃','Sheet Layout'],['썸네일 + 메타데이터','Thumbnail + metadata'],['상세 분석','Detailed'],['2개 비교','Compare 2'],['4개 비교','Compare 4'],['미리보기','Preview'],['사이트명','Site'],['선택한 캡처','Selected Captures'],['문서를 만들고 있어요','Creating document'],['다운로드','Download'],['16:9 와이드스크린','16:9 widescreen'],
['캡처 보드','Capture Board'],['이미지 추가','Add Images'],['프로젝트 저장','Save Project'],['그리드 보기','Grid view'],['목록 보기','List view'],['전체','All'],['완료','Done'],['실패','Failed'],['사이트 검색','Search sites'],['해제','Deselect'],['선택','Select'],['페이지를 캡처하고 있어요','Capturing page'],['캡처를 완료하지 못했어요','Capture failed'],['캡처 대기 중','Waiting to capture'],['인사이트를 메모해 보세요…','Add an insight…'],
['좋은 리서치는, 링크 하나에서.','Great research starts with one link.'],['위에 URL을 입력하거나 샘플 프로젝트로 먼저 둘러보세요.','Enter URLs above or explore a sample project.'],['영감이 될 페이지들을 이곳에 모아 보세요.','Collect inspiring pages here.'],['이미지 비율, 제목, 링크까지. 바로 공유할 수 있는 슬라이드로 정리해요.','Create share-ready slides with images, titles, and links.'],['가입 없이 · 샘플 캡처 3개 · 문서 내보내기 체험','No signup · 3 sample captures · Try document export'],['샘플 프로젝트 열어보기','Open Sample Project'],['도움이 필요하신가요?','Need help?'],['알림 닫기','Close notification'],['닫기','Close'],['이미지 저장','Save Image'],['데스크톱 실행 안내','Desktop Setup Guide'],['샘플로 체험하기','Try a Sample'],['로그인할 사이트 URL','Site URL to sign in'],['캡처할 URL 목록','URLs to capture'],['로그인 창 열기','Open Login Window'],
['실제 웹 캡처는 내 기기에서.','Capture websites on your device.'],['링크에서 보고서까지, 세 단계.','From links to reports in three steps.'],['새로운 리서치','New Research'],['디자인 벤치마킹 · 샘플','Design Benchmark · Sample'],['올바른 URL을 입력해 주세요.','Enter a valid URL.'],['캡처할 URL을 추가해 주세요.','Add a URL to capture.'],['캡처할 CSS 선택자를 입력해 주세요.','Enter a CSS selector to capture.'],['내보내기 실패:','Export failed:'],['URL이나 캡처를 먼저 추가해 주세요.','Add URLs or captures first.'],['이 기기의 보관함에 저장했습니다.','Saved to this device.']
] as const;
const dictionaries={en:Object.fromEntries(pairs),ko:Object.fromEntries(pairs.map(([ko,en])=>[en,ko]))};
const swap=(value:string,locale:Locale)=>Object.entries(dictionaries[locale]).sort(([a],[b])=>b.length-a.length).reduce((text,[from,to])=>text.includes(from)?text.split(from).join(to):text,value);
function apply(root:ParentNode,locale:Locale){const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node:Node|null;while((node=walker.nextNode()))if(node.nodeValue?.trim()&&!node.parentElement?.closest('[data-no-translate]'))node.nodeValue=swap(node.nodeValue,locale);root.querySelectorAll<HTMLElement>('[placeholder],[aria-label],[title]').forEach(el=>['placeholder','aria-label','title'].forEach(name=>{const value=el.getAttribute(name);if(value)el.setAttribute(name,swap(value,locale));}));}
export function getInitialLocale():Locale{const saved=localStorage.getItem(key);return saved==='ko'||saved==='en'?saved:navigator.language.toLowerCase().startsWith('ko')?'ko':'en';}
export const setSavedLocale=(locale:Locale)=>localStorage.setItem(key,locale);
export function installTranslations(locale:Locale){document.documentElement.lang=locale;apply(document.body,locale);const observer=new MutationObserver(records=>{observer.disconnect();records.forEach(record=>{if(record.target.parentNode)apply(record.target.parentNode,locale);record.addedNodes.forEach(node=>node.parentNode&&apply(node.nodeType===Node.ELEMENT_NODE?node as ParentNode:node.parentNode,locale));});observer.observe(document.body,{subtree:true,childList:true,characterData:true});});observer.observe(document.body,{subtree:true,childList:true,characterData:true});return()=>observer.disconnect();}
