import http from 'node:http';
import {mkdir,writeFile} from 'node:fs/promises';
import {CaptureEngine} from '../core/capture.mjs';
const base=`*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif}nav{height:105px;display:flex;align-items:center;justify-content:space-between;margin:0 70px;border-bottom:1px solid currentColor}nav strong{font-size:28px;letter-spacing:-1px}nav span{font-size:13px;word-spacing:30px}main{padding:80px 70px}small{font-size:12px;letter-spacing:3px}h1{font-size:105px;line-height:1.03;letter-spacing:-7px;font-weight:500;margin:36px 0}p{font-size:20px;line-height:1.65;max-width:500px}footer{padding:30px 70px;display:flex;justify-content:space-between;font-size:12px}a{display:inline-block;padding:18px 26px;border-radius:30px;border:1px solid;margin-top:20px;font-size:14px}`;
const pages={
  studio:`<!doctype html><title>North Studio</title><style>${base}body{background:#dcebcb;color:#243921}main{display:flex;align-items:center;gap:100px}h1{font-size:114px}.right{border-top:1px solid #668157;padding-top:24px;align-self:flex-end;margin-bottom:30px}h2{font-size:36px;font-weight:400;line-height:1.3}main>div:first-child{flex:1}.right p{font-size:16px;max-width:300px}footer{border-top:1px solid #b1c7a0}</style><nav><strong>north®</strong><span>STUDIO WORK JOURNAL CONTACT</span></nav><main><div><small>INDEPENDENT DESIGN STUDIO</small><h1>Good design.<br>Better<br>possibilities.</h1><a>Discover our work ↗</a></div><div class="right"><small>01 / OUR APPROACH</small><h2>Thoughtful by nature.<br>Distinct by design.</h2><p>We build brands and digital experiences that connect people to a world worth creating.</p></div></main><footer><span>STRATEGY · BRANDING · DIGITAL</span><span>SEOUL / EVERYWHERE</span></footer>`,
  forma:`<!doctype html><title>Forma</title><style>${base}body{background:#faf8f4;color:#362c25}main{padding-top:85px;text-align:center}h1{font-size:105px;letter-spacing:-6px}main p{margin:30px auto;font-size:19px;color:#8a796a}a{background:#563e2d;color:#fff}nav{border-color:#e0d9cf}.tags{display:flex;justify-content:center;gap:65px;margin-top:65px;border-top:1px solid #e3dbd2;padding-top:35px;color:#9b8d7e;font-size:13px;letter-spacing:2px}footer{margin-top:32px}</style><nav><strong>forma.</strong><span>OUR SPACES MEMBERSHIP ABOUT</span></nav><main><small>ROOM FOR YOUR NEXT CHAPTER</small><h1>A space to think.<br>A place to grow.</h1><p>Considered workspaces for curious minds.<br>Find your focus, your people, and your next idea.</p><a>Find your space ↗</a><div class="tags"><span>THOUGHTFULLY DESIGNED</span><span>FLEXIBLY YOURS</span><span>LOCALLY CONNECTED</span></div></main><footer><span>MAKE ROOM FOR WHAT MATTERS.</span><span>EST. 2026</span></footer>`,
  journal:`<!doctype html><title>Fieldnotes</title><style>${base}body{background:#191e24;color:#eef0ed}nav{border-color:#3b4145}main{padding-top:65px}h1{font-size:103px;margin:28px 0 48px}.articles{display:grid;grid-template-columns:1fr 1fr 1fr;border-top:1px solid #4b5356}.articles>div{padding:28px 32px 0 0;margin-right:30px}.articles small{color:#8caba1;font-size:10px}.articles h2{font-size:28px;line-height:1.3;font-weight:400}.articles p{font-size:14px;color:#a5b0af}footer{color:#a3b3af;border-top:1px solid #3b4547}</style><nav><strong>fieldnotes /</strong><span>STORIES PERSPECTIVES ABOUT</span></nav><main><small>AN INDEPENDENT JOURNAL OF IDEAS</small><h1>Stay curious.<br>Look a little closer.</h1><div class="articles"><div><small>01 · DESIGN</small><h2>The beauty of<br>paying attention.</h2><p>Finding extraordinary ideas in the everyday.</p></div><div><small>02 · CULTURE</small><h2>A slower kind<br>of progress.</h2><p>On making space for what really matters.</p></div><div><small>03 · PERSPECTIVE</small><h2>Things we choose<br>to keep.</h2><p>A collection of meaningful observations.</p></div></div></main><footer><span>IDEAS WORTH COLLECTING.</span><span>VOLUME 01 — 2026</span></footer>`
};
const server=http.createServer((req,res)=>{res.setHeader('content-type','text/html');res.end(pages[req.url.slice(1)]||pages.studio);});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
await mkdir('public/samples',{recursive:true});
try{const engine=new CaptureEngine();const results=[];await engine.run(Object.keys(pages).map(id=>({id,url:`http://127.0.0.1:${server.address().port}/${id}`})),{mode:'viewport',device:'laptop',clean:false,concurrency:3},item=>{if(item.status==='done')results.push(item);if(item.status==='error')console.error(item);});for(const item of results){await writeFile(`public/samples/${item.id}.jpg`,Buffer.from(item.image.split(',')[1],'base64'));}if(results.length!==3)throw new Error('Sample generation failed');console.log('Created 3 genuine sample page captures.');}finally{server.close();}
